### ISSUE TITLE
lambdaのenvからssm secretにACCESS_TOKENに移してみる

### ISSUE THREAD

**Issue by RyosukeDTomita** [RyosukeDTomita/qiita_auto_update#7]
### New feature description

ACCESS_TOKENとはいえ，一応write権限必要だから直したほうが良いかなと

### solution

```shell
aws ssm put-parameter --name /path/to/secret --value "your_access_token" --type SecureString
```

```
service: my-service
provider:
  name: aws
  runtime: nodejs14.x

functions:
  myFunction:
    handler: handler.myFunction
    environment:
      ACCESS_TOKEN: ${ssm:/path/to/secret~true}
```
